[theme]
base = "dark"
primaryColor = "#FFB000"                     # Orange finance pro
backgroundColor = "#0B0B0B"                  # Noir profond
secondaryBackgroundColor = "#1E1E1E"         # Gris foncé pour les cards
textColor = "#F5F5F5"                        # Blanc cassé
font = "sans serif"

[general]
page_icon = "🧠"

[client]
showSidebarNavigation = false

[server]
headless = true